### ISSUE TITLE
Is it still working? 

### ISSUE THREAD

**Issue by aptonem** [Dhruvesh08/usa-visa-automation#1]
When I test it stucks on below line;
`const element = await waitForSelectors([["aria/Email *"],["#user_email"]], targetPage, { timeout, visible: true });`

I think, something has changed on the appointment web page but I don't know how to handle and change this line for related changes. Can you please help to update the working release?

**Comment by Dhruvesh08** [comment]
Thanks for the input 
as it seems for sure appointment page is change 
i'll take a look at it.
